name: Scrape Agmarknet Only via Tor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  agmarknet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Tor with ControlPort enabled
      run: |
        sudo apt-get update
        sudo apt-get install -y tor python3 python3-pip
        sudo systemctl stop tor
        echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
        echo "CookieAuthentication 1" | sudo tee -a /etc/tor/torrc
        sudo systemctl start tor
        echo "Tor with ControlPort started"

    - name: Export Tor proxy for Playwright
      run: |
        echo 'export http_proxy=socks5h://127.0.0.1:9050' >> $GITHUB_ENV
        echo 'export https_proxy=socks5h://127.0.0.1:9050' >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        pip install playwright==1.42.0
        playwright install chromium
        pip install beautifulsoup4 stem "requests[socks]"

    - name: Run Agmarknet Scraper via Tor
      run: |
        python3 scrape_agmarknet_gov_in.py
