name: Scrape Agmarknet Only via Tor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM UTC

jobs:
  agmarknet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Tor and Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tor python3 python3-pip
        sudo systemctl start tor
        echo "Tor started"

        echo 'export http_proxy=socks5h://127.0.0.1:9050' >> $GITHUB_ENV
        echo 'export https_proxy=socks5h://127.0.0.1:9050' >> $GITHUB_ENV

    - name: Install Python packages
      run: |
        pip install playwright==1.42.0
        playwright install chromium
        pip install beautifulsoup4 stem "requests[socks]"

    - name: Run Agmarknet scraper ONLY
      run: |
        python3 scrape_agmarknet_gov_in.py
