name: Scrape Agmarknet via Free Proxies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  agmarknet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python and Playwright
      run: |
        pip install playwright==1.42.0
        playwright install chromium
        pip install beautifulsoup4

    - name: Run Agmarknet Scraper with Free Proxy
      run: |
        python3 -u scrape_agmarknet_gov_in.py

    - name: Upload debug artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: agmarknet-debug
        path: debug/
