name: Scrape Agmarknet via ScraperAPI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  agmarknet:
    runs-on: ubuntu-latest

    env:
      SCRAPERAPI_KEY: ${{ secrets.SCRAPERAPI_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python and Playwright
      run: |
        pip install playwright==1.42.0
        playwright install chromium
        pip install beautifulsoup4

    - name: Run Agmarknet Scraper via ScraperAPI
      run: python3 -u scrape_agmarknet_gov_in.py

    - name: Upload debug screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: agmarknet-debug
        path: debug/
